import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../../styles/Home.module.css';

const defaultEndpoint = `https://rickandmortyapi.com/api/episode/`;

export async function getServerSideProps( {query} ) {
  const { id } = query;
  const res = await fetch(`${defaultEndpoint}/${id}`);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}


export default function Character( { data }) {
  const { name, air_date, episode, characters } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        {name}
        </h1>
        <div className={styles.profile}>
          <div className={styles.profileDetails}>
            <h2>Episode Details</h2>
            <ul>
              <li>
                <strong>Name:</strong> { name }
              </li>
              <li>
                <strong>Air Date:</strong> { air_date }
              </li>
              <li>
                <strong>Season: </strong> { episode }
              </li>
            </ul>
          </div>
        </div>
        <p className={styles.back}>
          <Link href="/episodes">
            <a>
              Back to All Episodes
            </a>
          </Link>
        </p>
      </main>

    </div>
  )
}
