import { useState, useEffect } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../../styles/Home.module.css';
import Header from "../../../components/Header/Header"

const defaultEndpoint = `https://rickandmortyapi.com/api/episode/`;

export async function getServerSideProps( {query} ) {
  const { id } = query;
  const res = await fetch(`${defaultEndpoint}/${id}`);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}


export default function Character( { data }) {
  const { name, air_date, episode, characters } = data;
  const [charactersInfo, setCharactersInfo] = useState([]);

  useEffect(() => {
    async function fetchAll() {
      const results = await Promise.all(characters.map((url) => fetch(url).then((r) => r.json()))).then(data => setCharactersInfo(data));
    }
    fetchAll();
  }, [])
  

  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
        {name}
        </h1>
        <div className={styles.profile}>
          <div className={styles.profileDetails}>
            <h2>Episode Details</h2>
            <ul>
              <li>
                <strong>Name:</strong> { name }
              </li>
              <li>
                <strong>Air Date:</strong> { air_date }
              </li>
              <li>
                <strong>Season: </strong> { episode }
              </li>
            </ul>
          </div>
        </div>
        <p className={styles.back}>
          <Link href="/episodes">
            <a>
              Back to All Episodes
            </a>
          </Link>
        </p>
        <ul className={styles.grid}>
            {charactersInfo.map(result => {
              const { id, name, image, status } = result;
              return (
                <li key={id} className={styles.card}>
                  <Link href="/character/[id]" as={`/character/${id}`} >
                    <a className={styles.linkContainer}>
                      <p 
                      className={styles.status} 
                      style={status === "Alive" ? {backgroundColor : "#2b9348"} 
                      : status === "Dead" ? {backgroundColor : "#e5383b"}
                      : {backgroundColor : "#5829a7"}}>
                        {status}
                      </p>
                      <img src={image} alt={`${name} Thumbnail`} />
                      <h3>{ name }</h3>
                    </a>
                  </Link>
                </li>
              )
            })}
          </ul>
      </main>

    </div>
  )
}
